build:
	gcc -g -Wall -c -static is_empty.c len_diff.c myHeap.c numinrange.c pad.c ptr_to.c repeat.c replace.c rm_empties.c rm_leftS.c rm_rightS.c rm_space.c shorten.c strmod.c str_zip.c suffIgn.c take_last.c
